//! Build-script story indexer for [`dioxus-storybook`].
//!
//! # Why a build script at all
//!
//! JavaScript can do `import.meta.glob('**/*.stories.js')`. Rust links
//! everything at compile time, and the two obvious workarounds both fail on the
//! target that matters:
//!
//! | Mechanism | `wasm32` release | `wasm32` debug (`dx serve`) |
//! |---|---|---|
//! | `linkme` 0.3 | does not compile | does not compile |
//! | `inventory` 0.3 | passes | **silently drops stories** |
//! | build-script codegen | passes | passes |
//!
//! `inventory` is the dangerous one: registration is lost for any story in a
//! codegen unit nothing else references, which bisects cleanly on
//! `codegen-units` — 1 passes, 16 and 256 fail. Release uses one unit and dev
//! uses 256, so stories vanish while you develop and reappear in production.
//!
//! This crate emits explicit `&'static` references instead, which no linker
//! decision can drop. (Measured in the M0 S2 spike; see `log/0002-m0-spikes.md`.)
//!
//! # Usage
//!
//! In `build.rs`:
//!
//! ```no_run
//! fn main() {
//!     dioxus_storybook_build::index("src/stories").unwrap();
//! }
//! ```
//!
//! In `main.rs`:
//!
//! ```ignore
//! mod stories {
//!     include!(concat!(env!("OUT_DIR"), "/dioxus_storybook_registry.rs"));
//! }
//! ```
//!
//! The generated file both *declares* the story modules and references their
//! statics, so adding `src/stories/card.rs` is enough to make its stories
//! appear — there is no `mod.rs` to maintain. Do not also declare those files as
//! modules yourself; they would be compiled twice.

#![deny(missing_docs)]

mod scan;

use std::path::{Path, PathBuf};
use std::{env, fs, io};

pub use scan::story_fns;

/// The name of the file written into `OUT_DIR`.
pub const GENERATED_FILE: &str = "dioxus_storybook_registry.rs";

/// The `StoryDef` static that `#[story] fn primary()` generates.
///
/// The macro and this crate have to agree on this, so it lives in one place.
///
/// ```
/// # use dioxus_storybook_build::static_ident_for;
/// assert_eq!(static_ident_for("with_icon"), "WITH_ICON");
/// ```
pub fn static_ident_for(fn_name: &str) -> String {
    fn_name.to_uppercase()
}

/// What [`index`] found, returned so a build script can assert on it.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Index {
    /// Story files that were scanned, in path order.
    pub files: Vec<PathBuf>,
    /// Every story, as `(module ident, static ident)`.
    pub stories: Vec<(String, String)>,
}

impl Index {
    /// How many stories were indexed.
    pub fn len(&self) -> usize {
        self.stories.len()
    }

    /// `true` if no stories were found.
    pub fn is_empty(&self) -> bool {
        self.stories.is_empty()
    }
}

/// Scan `dir` for `#[story]` functions and write the registry into `OUT_DIR`.
///
/// Emits the `cargo:rerun-if-changed` lines that make adding, editing or
/// deleting a story file rebuild the registry.
///
/// A missing or empty directory is not an error — a project can legitimately
/// have no stories yet — but it does produce a build warning, because an empty
/// sidebar is nearly always a wiring mistake.
pub fn index(dir: impl AsRef<Path>) -> io::Result<Index> {
    let manifest = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR")
            .map_err(|_| io::Error::other("CARGO_MANIFEST_DIR is unset; run this from build.rs"))?,
    );
    let out_dir = PathBuf::from(
        env::var("OUT_DIR")
            .map_err(|_| io::Error::other("OUT_DIR is unset; run this from build.rs"))?,
    );

    let root = manifest.join(dir.as_ref());
    println!("cargo:rerun-if-changed={}", root.display());

    let mut files = Vec::new();
    collect_rs_files(&root, &mut files);
    files.sort();

    let mut index = Index::default();
    let mut decls = String::new();
    let mut refs = String::new();

    for (n, file) in files.iter().enumerate() {
        println!("cargo:rerun-if-changed={}", file.display());
        let src = fs::read_to_string(file)?;
        let fns = story_fns(&src);
        if fns.is_empty() {
            continue;
        }

        let module = format!("__dxsb_file_{n}");
        decls.push_str(&format!(
            "#[path = {:?}]\npub mod {module};\n",
            file.to_string_lossy()
        ));
        for f in fns {
            let static_ident = static_ident_for(&f);
            refs.push_str(&format!("    &{module}::{static_ident},\n"));
            index.stories.push((module.clone(), static_ident));
        }
        index.files.push(file.clone());
    }

    if index.is_empty() {
        println!(
            "cargo:warning=dioxus-storybook: no #[story] functions found under {} — the sidebar will be empty",
            root.display()
        );
    }

    let generated = format!(
        "// @generated by dioxus-storybook-build — do not edit.\n\
         // Source of truth: the #[story] functions under {}\n\
         {decls}\n\
         /// Every story found at build time, in file order.\n\
         pub static STORIES: &[&'static ::dioxus_storybook::StoryDef] = &[\n{refs}];\n\
         \n\
         /// The registry to hand to `Storybook`.\n\
         pub fn registry() -> ::dioxus_storybook::Registry {{\n\
         \x20   ::dioxus_storybook::Registry::new(STORIES)\n\
         }}\n",
        root.display()
    );

    fs::write(out_dir.join(GENERATED_FILE), generated)?;
    Ok(index)
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rs_files(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}
