//! Stand-in for `dx-story`'s indexer. Walks the story tree, finds every
//! `story!(IDENT, ...)` declaration, and emits a flat registry of explicit
//! references. This is what the real CLI will do across a workspace.

use std::{env, fs, path::{Path, PathBuf}};

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() { walk(&p, out); }
        else if p.extension().is_some_and(|x| x == "rs")
             && p.file_name().is_some_and(|f| f != "mod.rs") { out.push(p); }
    }
}

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/stories");
    println!("cargo:rerun-if-changed=src/stories");

    let mut files = Vec::new();
    walk(&root, &mut files);
    files.sort();

    let mut refs = Vec::new();
    for f in &files {
        println!("cargo:rerun-if-changed={}", f.display());
        let rel = f.strip_prefix(&root).unwrap().with_extension("");
        let module: Vec<String> = rel.components()
            .map(|c| c.as_os_str().to_string_lossy().into_owned()).collect();
        let path = format!("crate::stories::{}", module.join("::"));

        let src = fs::read_to_string(f).unwrap_or_default();
        for line in src.lines() {
            let t = line.trim_start();
            if let Some(rest) = t.strip_prefix("story!(") {
                if let Some(ident) = rest.split(',').next() {
                    let ident = ident.trim();
                    if !ident.is_empty() {
                        refs.push(format!("    &{path}::{ident},"));
                    }
                }
            }
        }
    }

    let generated = format!(
        "// @generated by build.rs — do not edit\n\
         pub static STORIES: &[&'static s2_cg_core::StoryDef] = &[\n{}\n];\n",
        refs.join("\n")
    );
    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("stories_generated.rs");
    fs::write(&dest, generated).unwrap();
    println!("cargo:warning=indexed {} stories from {} file(s)", refs.len(), files.len());
}
